if($<CONFIG> STREQUAL "Debug")
    set(DIRECTXMATH_CONFIG "Debug")
elseif($<CONFIG> STREQUAL "Release" OR $<CONFIG> STREQUAL "MinSizeRel" OR $<CONFIG> STREQUAL "RelWithDebInfo")
    set(DIRECTXMATH_CONFIG "Release")
endif()

set(DIRECTXMATH_ROOT_PATH "${CMAKE_CURRENT_SOURCE_DIR}/../..")
set(DIRECTXMATH_RUNTIME_ID "win11-msvc-x64")
set(DIRECTXMATH_RUNTIME_PATH "${DIRECTXMATH_ROOT_PATH}/runtimes/win11/msvc/x64/")
set(DIRECTXMATH_INCLUDE_PATH "${DIRECTXMATH_ROOT_PATH}/runtimes/win11/msvc/x64/include/")

target_include_directories(${PROJECT_NAME} PRIVATE ${DIRECTXMATH_INCLUDE_PATH})
